### PR TITLE
Trezor.Net

### PR DESCRIPTION
**Pull request by MelbourneDeveloper**
Trezor is a crypto Hardwarewallet, and Trezor.Net is library for talking to it.

https://github.com/MelbourneDeveloper/Trezor.Net

### CODE REVIEW

**Comment by ngohungphuc** [comment]
Close this pr due to inactivity

**Comment by MelbourneDeveloper** [comment]
@ngohungphuc I have fixed the readme on the repo. Could you please review this again?

https://github.com/MelbourneDeveloper/Trezor.Net

**Comment by ngohungphuc** [comment]
@thangchung

**Comment by thangchung** [comment]
@MelbourneDeveloper I have seen the description as your readme as below

`
This library allows you to communicate with both Trezor hardwarewallets in the same way that the Trezor browser wallet app communicates with them. It can be used to build apps that send or receive crypto currencies like Bitcoin in a secure way.
`

And it should be the wallet for https://trezor.io, right?

**Comment by MelbourneDeveloper** [comment]
Yep

**Comment by MelbourneDeveloper** [comment]
@thangchung enough info now?

**Comment by thangchung** [comment]
@MelbourneDeveloper Okay. I'm happy to merge it. Thank you for your hard working 👍

**Pull request merged**
