### PR TITLE
Add Template Engines

### PR DESCRIPTION
**Pull request by Leon99**

### CODE REVIEW

**Comment by thangchung** [comment]
@Leon99 Thank you for your PR. Please help to move it to **Misc** section, and we follow the alphabet order also

**Comment by Leon99** [comment]
I thought we want to keep the same section as awesome-dotnet, to make it simpler to match the lists?

**Comment by thangchung** [comment]
@Leon99 I know your thinking, but actually we are doing different ways with what awesome-dotnet did, man :)

**Comment by Leon99** [comment]
Why, if I may ask?

**Comment by thangchung** [comment]
The first starting point of this project is quite simple, and I want to make it better categorizes (to awesome-dotnet because there is a lot of projects did not run in .NET Core so far) so that readers can be easy to find the things they need. The items in this list now quite clumsy, I haven't enough time to take a look and re-organize it - will do it in next couple of days. If you want to add a new section, that is okay as long as you think that is good for readers.

**Comment by LordMike** [comment]
I concur. Template engines are a big category of projects on its own, and when we recently needed to find a template engine for a project at work, I actually went to this list to find it and found none.

There are a few template engines now, so a category might be due?

**Comment by ngohungphuc** [comment]
@Leon99 please resolve conflict so we can merge this one

**Comment by Leon99** [comment]
Hmm @ngohungphuc I see that DotLiquid has already been added, so this PR is not needed anymore.

**Comment by ngohungphuc** [comment]
@Leon99 thank I will close this PR

**Pull request closed without merging**
