### PR TITLE
Add https://github.com/ImVexed/NotLiteCode

### PR DESCRIPTION
**Pull request by ImVexed**

### CODE REVIEW

**Comment by ImVexed** [comment]
Bump

**Comment by thangchung** [comment]
@ImVexed Thank you for your PR. I have seen that that project was quite not updated or committed over 3 months ago. Do you still working on it?

**Comment by ImVexed** [comment]
Yes

**Comment by ImVexed** [comment]
Disregard, I no longer want to be added to this list. This entire process seems entirely subjective with no clear guidelines for acceptance criteria and that's not something I want to contribute to.

**Pull request closed without merging**
