### PR TITLE
added Toucan application template

### PR DESCRIPTION
**Pull request by mrellipse**
Hello. Just wanted to add my boilerplate solution to share with anyone in OSS working with .net core.

It has a yeoman generator project now, which should help out.

Any question just let me know!

### CODE REVIEW

**Comment by Jogai** [comment]
Comparing with https://github.com/aspnet/JavaScriptServices (Also has vue and uses TS), what did you do different?

**Comment by mrellipse** [comment]
Well, in terms of differences, it is a lot more feature rich than that one. 

The yeoman generator doesn't output a starting 'template', but a functional SPA site with a lot of popular VueJs community packages baked in. 

- localization (vue-i18n)
- validation (vuelidate)
- global application state/event bus (vuex)
- token-based authentication (JWT)
- multiple entry points (ie. sub-sites)
- support for local or external authentication providers (google, microsoft)

The back-end is multi-project, along SOLID development lines. It's opinionated, but also a big time saver!

**Comment by thangchung** [comment]
@mrellipse So it's only for VueJS, right? Any famous front-end libraries (Angular, React...) can leverage this stack?

**Comment by mrellipse** [comment]
I basically wanted to build an application that doesn't rely on any
server-side rendering. No razor views

So the .Net Core application is fulfilling just two roles

- serves static content
- serves api data from various endpoints

No plans to build an angular or react-based version for the ui ...

**Comment by thangchung** [comment]
@mrellipse I am happy to merge this PR. Thank you for your awesome works 👍

**Comment by mrellipse** [comment]
👍  for curating, and spread OSS goodness!

**Pull request merged**
