### PR TITLE
code formatter

### PR DESCRIPTION
**Pull request by hanabi1224**

### CODE REVIEW

**Comment by LordMike** [comment]
Why on earth did you change the large list from stars to dashes?

Initially I thought you ran the formatter on the md file, but then all other lists use stars also .. :|

**Comment by hanabi1224** [comment]
@LordMike I was using VS code to edit the file and it formatted the file automatically >_<

**Comment by hanabi1224** [comment]
@LordMike  Unexpected changes are all reverted, please take another look

**Comment by fidergo-stephane-gourichon** [comment]
[Squash and Merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) to the rescue?

**Comment by hanabi1224** [comment]
@fidergo-stephane-gourichon  yes please

**Comment by thangchung** [comment]
@hanabi1224 Two things, I would like to ask you. Firstly, I have seen that this lib is target to `<TargetFramework>net46</TargetFramework>`, but this repository is for .NET Core actually. Is there any additionally one for .NET Core?. Secondly, we follow alphabet order, so please change it if we all agree on the first point. Thank you very much 👍

**Comment by hanabi1224** [comment]
@thangchung  This is a compile-time only build task that formats the code but does not produce any output, so it does support dotnet core, The build environment has to be windows tho

**Comment by thangchung** [comment]
Thank you all participants to make this repo more useful. I'm happy to merge

**Pull request merged**
