### PR TITLE
Added JustA.ML

### PR DESCRIPTION
**Pull request by mustakimali**

### CODE REVIEW

**Comment by thangchung** [comment]
@mustakimali Look cool, guy. But we have a rule in this repo as

> Notes: The repository in github or any source control should be created at least 3 months.

You can have a look at that at https://github.com/thangchung/awesome-dotnet-core/blob/master/contributing.md,  I will keep your PR at here, please do some of the advertising for your repo in the community, I will come back later. Thank you again for your PR.

**Comment by mustakimali** [comment]
Apologies for this, haven't read this rule this time. I agree it's a good idea to allow projects older than certain age to maintain the quality of projects being showcased here. Awesome :)

**Comment by thangchung** [comment]
@mustakimali Thanks. I will keep your PR opening, and revisit it after that. Anw it is very cool lib 👍

**Comment by thangchung** [comment]
I just run the demo azure website. It is really cool. I am happy to merge it. Thank you very much and hope you can contribute more to this repo 👍

**Pull request merged**
