### PR TITLE
Add CliWrap

### PR DESCRIPTION
**Pull request by Tyrrrz**

### CODE REVIEW

**Comment by thangchung** [comment]
@Tyrrrz Hello. I have reviewed your lib, look cool. We follow the alphabet order, so could you change the order of it?

**Comment by Tyrrrz** [comment]
Hello. Sorry, didn't notice. Change the order.

**Comment by Tyrrrz** [comment]
Can this be merged now or is there something else?

**Comment by thangchung** [comment]
Yes, I do it now. Sorry for a long time no actions.

**Pull request merged**
