### PR TITLE
Add YoutubeExplode

### PR DESCRIPTION
**Pull request by Tyrrrz**

### CODE REVIEW

**Comment by thangchung** [comment]
That's cool lib. One question for you, is it a wrapper of YouTube API? If it is, please change it to **SDKs* section. Thank you.

**Comment by Jogai** [comment]
Its not according to the project page

**Comment by Tyrrrz** [comment]
It's not a wrapper for the official API, no.

**Comment by Tyrrrz** [comment]
Can it be merged now?

**Comment by thangchung** [comment]
Yes, we can. Thank you for your PR.

**Pull request merged**
