### PR TITLE
Orchard Core

### PR DESCRIPTION
**Pull request by agriffard**
Edit Orchard Core CMS and add Orchard Core in Application Frameworks.

### CODE REVIEW

**Comment by thangchung** [comment]
Nice catch 👍  
But why don't you put *OrchardCore.Samples* project into **Sample Projects** section. Let me know how do you think? Thank you.

**Comment by agriffard** [comment]
It is on purpose: OrchardCore.Samples is a solution that explains how to create a modular and a multi-tenant project just by using the **OrchardCore Application Framework** packages, without all the CMS modules.

**Comment by thangchung** [comment]
So for that purpose, it should be in the sub of Orchard project on this list, just like the EFCore in this list.

**Comment by agriffard** [comment]
OK, I changed the description and added some links in Samples and Articles section

**Comment by thangchung** [comment]
Thank you. I am happy to merge it 👍

**Pull request merged**
