### PR TITLE
Adding SqlKata under Orm

### PR DESCRIPTION
**Pull request by ahmad-moussawi**
SqlKata - Elegant Sql Query Builder, that supports complex queries, joins, sub queries, nested where conditions, vendor engine targets and more

[https://sqlkata.com](https://sqlkata.com)

### CODE REVIEW

**Comment by thangchung** [comment]
I just had a look at that. Look cool, but could you please change the link to GitHub link?

**Comment by ahmad-moussawi** [comment]
@thangchung thanks, link updated

**Comment by thangchung** [comment]
@ahmad-moussawi We follow the alphabet order, could you change the order of your lib up above of the **yessql** lib, please!

**Comment by ahmad-moussawi** [comment]
Yes sure, done

**Comment by thangchung** [comment]
@ahmad-moussawi I don't think we need to introduce the new section (**Query Builders**) in this case. I think the query builder is an abstraction on the top of the code that generating the T-SQL on the behind of it. So that the correct place to put it here should be in **ORM** section. Let me know how do you think?

**Comment by ahmad-moussawi** [comment]
@thangchung, I think it cannot be considered as an ORM, since it doesn't know anything on how to map an object (or model) to a table, or how to define relations between different models, it's just a dummy query builder with no additional meta about the underlying database (even you can write a query against a non existing table which not the case for ORMs), so I think it doesn't represent a good fit for ORMs.

**Pull request merged**
