### PR TITLE
Add Eighty to Misc

### PR DESCRIPTION
**Pull request by DenisPav**
Add https://github.com/benjamin-hodgson/Eighty

### CODE REVIEW

**Comment by thangchung** [comment]
It is a very good project, but we have a rule that repo on GitHub needs to be created at least 3 months. I will have an eye on your PR. Thank you for your contribution 👍

**Comment by DenisPav** [comment]
Ohh totally fogot about it. Sure lets have it sit here until then 😄

**Comment by ngohungphuc** [comment]
@DenisPav please resolve conflict

**Comment by DenisPav** [comment]
@ngohungphuc It should be okay now

**Pull request merged**
