### PR TITLE
Adding netDumbster to the Mail list.

### PR DESCRIPTION
**Pull request by cmendible**
[netDumbster](https://github.com/cmendible/netDumbster) - a .Net Fake SMTP Server used for testing. Clone of the popular Dumbster.

Over 82.000 downloads from [nuget.org](https://www.nuget.org/packages/netDumbster/)

Hope it helps!

### CODE REVIEW

**Comment by thangchung** [comment]
@cmendible This is the cool lib. But could you please change the order of this lib a bit? We follow alphabet order. Thank you.

**Comment by cmendible** [comment]
Hi @thangchung any news on this one?

**Comment by cmendible** [comment]
Is this still **invalid**?

**Comment by thangchung** [comment]
@cmendible Sorry about long time no visit your PR. I've merged now. Thank you for your contribution 👍

**Pull request merged**
