### PR TITLE
add odata link

### PR DESCRIPTION
**Pull request by ngohungphuc**

### CODE REVIEW

**Comment by thangchung** [comment]
@ngohungphuc I just consider could we find the source code repository for the link and the current documentation page for the guidance? This will make the reader easy to find out the source code. Let me know how do you think.

**Comment by ngohungphuc** [comment]
@thangchung the main repo for odata is https://github.com/OData/WebApi

**Comment by ngohungphuc** [comment]
@thangchung  please help me review this pr and these 2 pr
https://github.com/thangchung/awesome-dotnet-core/pull/184
https://github.com/thangchung/awesome-dotnet-core/pull/185
Thank you

**Comment by ngohungphuc** [comment]
@thangchung please help me review this pr

**Comment by totht91** [comment]
I think this library is not currently supported on .NET Core framework: https://github.com/OData/WebApi/issues/939

Also the link is not good as you suggested.

**Comment by ngohungphuc** [comment]
They just release the beta here http://odata.github.io/WebApi/#14-01-netcore-beta1

**Comment by thangchung** [comment]
@totht91 Thanks for your help to answer.
@ngohungphuc In this case, I think it will be good if you can change the link to https://github.com/OData/WebApi/tree/feature/netcore. To my point of view, when I research about ODATA, it is really hard for me to find out the code for .NET Core. Thanks

**Comment by ngohungphuc** [comment]
@thangchung I just updated the link please help me review it

**Pull request merged**
