### PR TITLE
Add DevExpress XPO ORM to readme.md

### PR DESCRIPTION
**Pull request by dennis-garavsky**
I want to add it to the list of ORM, because DevExpress XPO supports .NET Standard 2.0/Core from the end of 2017 and it was also made [free-of-charge in 2018](https://community.devexpress.com/blogs/xpo/archive/2018/05/21/xpo-free-of-charge-in-v18-1.aspx) + [available on Nuget](https://www.nuget.org/packages/DevExpress.Xpo/).

### CODE REVIEW

**Comment by dennis-garavsky** [comment]
@thangchung , Hello, do you need more information to be able to merge this? Thank you for your help in advance.

**Comment by ngohungphuc** [comment]
Hi @dennis-garavsky does it have github repo ? You provide a link that related to open source repo.

**Comment by dennis-garavsky** [comment]
@thangchung, no, it does not have a GitHub repo, because this product is NOT open-source. Its use is FREE, but its source code is NOT shared. You can use the following download links: https://www.nuget.org/packages/DevExpress.Xpo/ and https://www.devexpress.com/Products/Try/ (free offline installer).

If you are interested in the product history, support, documentation, demos and other info, check my message here: https://github.com/quozd/awesome-dotnet/pull/704

Let me know if you need anything else to be able to merge this. Thank you in advance.

**Comment by ngohungphuc** [comment]
Yes I know but this repo intended to share free resource so everyone can get access to it.
@thangchung what do you think about this

**Pull request closed without merging**
