### PR TITLE
Add Funogram library to the Bot section

### PR DESCRIPTION
**Pull request by worldbeater**
Added Funogram Telegram Bot API library to the "Bot" section. There is also an article <a href="https://medium.com/@worldbeater/funogram-writing-telegram-bots-in-f-f27a873fa548">here</a> explaining how to get started with writing bots in functional style using .NET and F#.

### CODE REVIEW

**Comment by Rizzen** [comment]
Functional language libraries and frameworks are placed in Functional Programming category, maybe makes sense move Funogram there?

**Comment by worldbeater** [comment]
Yup, it seems this makes sense. **Bot** category seems to be only for bots and not for libs 😑

**Comment by ngohungphuc** [comment]
@worldbeater I think framework, SDK or lib to build Bot should be in bot section

**Comment by worldbeater** [comment]
Moved these two libraries to the Bot section! 👍

**Pull request merged**
