### PR TITLE
Removed dead .NET World link, added Facebook link.

### LINKED ISSUE #103: .NET World Video link problem
Under the **Videos** section, the [.NET World YouTube link](https://www.youtube.com/channel/UClW5uIyHKPhfSEloQxn7b0Q) leads to a terminated account with the following message:

> This account has been terminated due to multiple or severe violations of YouTube's policy against spam, deceptive practices, and misleading content or other Terms of Service violations. 

There is [a separate Facebook page here](https://www.facebook.com/dotnetworld.org) named "Dot NET World" which could be added to the **Community** section. I'm not sure if they're related, or if anybody might know who used to run the terminated YouTube page...

### PR DESCRIPTION
**Pull request by kmgallahan**
Resolves #103.

### CODE REVIEW

**Comment by Jogai** [comment]
Is a fb group really awesome?

**Comment by thangchung** [comment]
@Jogai Let me verify the FB group first

**Comment by kmgallahan** [comment]
@thangchung That's fine. This main point of this Issue and PR was to just remove the dead link from the list. 

I then sought out a ".NET World" link replacement out of respect for whoever originally added it, but that isn't particularly important.

**Comment by kmgallahan** [comment]
Closing this pull request as it doesn't appear to be going anywhere.

**Pull request closed without merging**
