### PR TITLE
Add Auth0 to Authentication section

### PR DESCRIPTION
**Pull request by jerriep**

### CODE REVIEW

**Comment by thangchung** [comment]
@jerriep Hi. I have a look at this PR. I think it should be a sample in the Sample Projects (https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples) or the Articles (https://auth0.com/docs/quickstart/webapp/aspnet-core), because it is not actually the library. How do you think?

**Comment by jerriep** [comment]
@thangchung Aaah, ok. Is your qualifying criteria that it should be written in .NET Core?

If so, we can perhaps change the link to instead link to the Auth0.NET SDK:
https://github.com/auth0/auth0.net

That is a .NET Standard library which talks to our underlying API.

Would that fix your concern?

**Comment by thangchung** [comment]
Yeah. I am happy if you can change it to https://github.com/auth0/auth0.net, it will make our audiences easy to references

**Comment by jerriep** [comment]
@thangchung OK, I have updated as you requested. Thanks 👍

**Pull request merged**
