### PR TITLE
add Lynicon to CMS section

### PR DESCRIPTION
**Pull request by jamesej**
Project at https://github.com/jamesej/lyniconanc.

### CODE REVIEW

**Comment by thangchung** [comment]
@jamesej Thank you for your PR. I have a look at your lib. One question for you now. Any point that you think your OSS is awesome?

**Comment by jamesej** [comment]
Many thanks @thangchung, yes it's awesome because it's the most flexible CMS I've ever seen.

**Comment by jamesej** [comment]
Let me expand on that - Lynicon is the core of a system which will be more powerful than any of your listed .net core CMSs, I am about to release a package of modules which will include common mid-range CMS features like publishing, search, caching, custom url management, and sitemap.
The core system supports a number of powerful content editing features:
- Arbitrarily nested JSON content data
- Content data can be sourced from database or held in-memory, and can be sourced and combined from multiple sources for which providers can easily be built
- Content data can be sourced from existing database tables
- Exceptionally clean integration with MVC, has minimal impact
- Designed to be possible to integrate into existing sites
- Built in asset management allows drag and drop onto Windows Explorer type asset manager window
- Designed for high performance

You can view the documentation at https://lynicon.atlassian.net/wiki/display/LAC/Overview

**Comment by thangchung** [comment]
@jamesej Correct me if I am wrong. I am paying attention to have a look at the documentation of this project (quite many things to read). I need to make sure it is the really cool project (not marketing the project at now, but I believe that if you do it well, then the people will love it).  As far as I know, this project comes from Atlassian, right?

**Comment by jamesej** [comment]
Hi @thangchung no it's my own project, I just have the documentation on Atlassian Confluence as it's a good tool to write public documentation.  The main site is at http://www.lynicon.com, the information there is less in-depth so might be better for ease of understanding.

**Comment by thangchung** [comment]
@jamesej I am happy to merge this PR. Thank for your great efforts 👍

**Pull request merged**
