### PR TITLE
Add a link to practical aspnetcore

### PR DESCRIPTION
**Pull request by dodyg**

### CODE REVIEW

**Comment by thangchung** [comment]
@dodyg Okay, Please ignore my comment in your issue. Thanks

**Comment by thangchung** [comment]
@dodyg Could you change `aspnetcore` to `ASP.NET Core` please? We will not use aspnetcore in all the awesome repo, due to not a standard word.

**Comment by dodyg** [comment]
OK done.

**Comment by thangchung** [comment]
@dodyg Okay. Welcome you to .NET Core awesome family 👍

**Pull request merged**
