### PR TITLE
Add FlubuCore

### PR DESCRIPTION
**Pull request by mzorec**
Git: https://github.com/flubu-core/flubu.core

Fluent builder a cross platform build automation tool for building projects and executing deployment scripts using C# code.

**Flubu main features / advantages**

- Net Core support (works also on linux and macOS).
- Easy to learn and to use because you write build script entirely in C#.
- Quite a lot of built in tasks (compile, running tests, managing iis, creating deploy package, publishing nuget packages, executing powershell scripts...)
- Write your own custom c# code in script and execute it.
- Run any external program in script.
- Reference any .net library or c# source code file in buildscript.
- Fluent interface and intelisense.
- Write tests, debug your build script.
- Use flubu tasks in any other application.
- Web api is available for flubu. Useful for automated deployments remotely.
- Write your own flubu tasks and extend flubu fluent interface with them.

### CODE REVIEW

**Comment by mzorec** [comment]
Just wondering what's the status with the PR?

**Comment by ngohungphuc** [comment]
@mzorec please resolve conflict. I'm reviewing it

**Comment by mzorec** [comment]
I have resolved conflict.

**Comment by ngohungphuc** [comment]
quick question do you have example to seed db for .net core

**Comment by mzorec** [comment]
No sorry I don't have example for sedding db at the moment but it shouldn't be problem do this with Flubu.

**Comment by mzorec** [comment]
I am not sure if u want to seed db with ef seeder or some other. I dont have example for that but if u want to initialize db with script I have example for that

```
SqlCmdTask task = new SqlCmdTask(fileName)
.SqlCmdExecutable(@"C:\Program Files\Microsoft SQL Server\110\Tools\Binn\SQLCMD.EXE")
.SqlCmdExecutable(@"C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\SQLCMD.EXE")
.Database(connInfo.Database)
.ForceUtf8()
.Server(connInfo.Server)
.WithArguments("-I");
```

SqlCmdTask is unfortunatlly missing in flubu fluent interface but it will be added in next version.

**Pull request merged**
