### PR TITLE
Add CakeMail.RestClient

### PR DESCRIPTION
**Pull request by Jericho**
Add CakeMail.RestClient which is a client for CakeMail's API. Allows you to send transactional emails, bulk emails, manage lists and contacts, etc.

### CODE REVIEW

**Comment by Jericho** [comment]
@thangchung do you plan to merge this PR?

**Comment by thangchung** [comment]
@Jericho Sorry for a long time no catch up with your PR. But please help to move it to **SDKs** section, because SendGrid client also put there. Thank you.

**Comment by Jericho** [comment]
I personally I think it makes more sense to have librairies in the section that best describe their utility rather than in a generic section called "SDK". For example, I believe that developers will be more inclined to look under the "Mail" section if they are looking for a library for SendGrid or CakeMail. But that's just my opinion. I'll move my library to the SDK section as you requested.

By the way, I quickly reviewed your awesome list and found other libraries in various sections instead of the SDK section. You should be consistent and move them to the SDK section as well. For example:

- Auth0 currently in the Authentication section
- Stripe currently in the E-Commerce section
- Exceptionless currently in the Exceptions section
- Exceptionless currently in the Logging section
- SendGrid Client in the Mail section
- StrongGrid in the Mail section

**Comment by thangchung** [comment]
@Jericho Thank you very much for your review, the list is quite big now so that is my mistake. I will move them to **SDKs** section then. Meanwhile, I will think about what you said, actually, we want to make our readers easier to find the useful things rather than make it for a personal usage.

**Comment by ngohungphuc** [comment]
Personally i will chose sendgrid instead this.

**Comment by Jericho** [comment]
Are you saying that you are not accepting my C# library for CakeMail because you personally would choose a different ESP?

**Comment by wernerbarnard** [comment]
@ngohungphuc I agree with @Jericho , my opinion would be that this repo should not be biased towards your personal choices (sendgrid in this case), but offer a complete list of valuable libraries / sdk's to users, as **the** primary reference when looking for something regarding dotnet core. (if that's the goal?)

PS. I don't even know what "CakeMail" is - if it's very minute towards the popular ESP's (Sendgrid, SparkPost, Mailgun, SES, etc) then maybe not, but assume it's not too small if @Jericho has put in the effort to write a library for it.

**Comment by thangchung** [comment]
@Jericho @wernerbarnard Yes, I agreed that we shall not biased on any libs as long as it helps people on their works.

@Jericho Is **CakeMail.RestClient** lib used in your project?

**Comment by Jogai** [comment]
Also, I wouldnt move too much to sdks. Grouped by their area of use is more helpful.

**Comment by Jericho** [comment]
@thangchung yes I do use it (and there are other users would are also using it).

**Comment by ngohungphuc** [comment]
@thangchung do you want to merge this pr

**Comment by Jericho** [comment]
@ngohungphuc why did you closed this PR without merging it?

**Comment by Jericho** [comment]
@thangchung what is the reason why this PR is being rejected? After the discussion in June I was left with the impression that it would be merged.

**Comment by thangchung** [comment]
@ngohungphuc Do we consider to re-open and merge it?

**Comment by Jericho** [comment]
@thangchung if you look at @ngohungphuc's [comment from June 12](https://github.com/thangchung/awesome-dotnet-core/pull/128#issuecomment-396545818), you'll see that he asked you if you wanted to merge. I'm guessing he closed this PR because you did not reply to him. I think someone just needs to make a decision whether you want my library on your list or not and if you you decide to reject my library, please tell me why so I can make the necessary correction.

**Comment by ngohungphuc** [comment]
I close it due to inactivity

**Pull request merged**
