### PR TITLE
Added https://github.com/ivanpaulovich/dotnet-clean-architecture

### PR DESCRIPTION
**Pull request by ivanpaulovich**
Hi @thangchung!

I added the project https://github.com/ivanpaulovich/dotnet-clean-architecture which demonstrates the basics of a Clean Architecture for a small set of use cases. It uses Model-View-Presenter to decouple Application from UI.

Thank you!

### CODE REVIEW

**Comment by thangchung** [comment]
@ivanpaulovich The project looks cool. But I'm sorry that it is quite new. I keep it at here and have a look after at least 3 months, will re-visit very soon

**Comment by ivanpaulovich** [comment]
@thangchung then we will take later :)
Thank you!

**Comment by ivanpaulovich** [comment]
> Would be nice if you can use generic repository for data access like TodoItemGateway.cs

Hi @ngohungphuc! Good feedback :)

I am probably going into the opposite direction, I think that when a class uses an interface it needs to consume all the methods.

For instance in the class `ListTodoItems` I am using only the `List` method of `ITodoItemGateway` which by following `ISP` then I will need to create a separated interface like `ITodoItemsQuery`.

In the end I will have dozens of interfaces but I like it hahaha

**Comment by thangchung** [comment]
@ivanpaulovich Hi Ivan. I come back to you now. Please help to change the order of your sample to alphabet order, then I would be happy to merge it

**Comment by ivanpaulovich** [comment]
Hey @thangchung,

I just updated the description and the list order.
I appreciate if you accept :)

**Pull request merged**
