### PR TITLE
Add Gofer.NET

### PR DESCRIPTION
**Pull request by brthor**
Add Gofer.NET background tasks library.

https://github.com/brthor/gofer.net

Gofer.NET is a focused library for background tasks with a very easy to use API.

### CODE REVIEW

**Comment by LordMike** [comment]
@brthor might I suggest that you move the Gofer core library into a project of its own. Currently, the project structure is a little messy (you have Utils and Tests _within_ the `Gofer.Net` project, with ignores / removes to hide them).

Once that's done - split out the core parts and the Redis implementation (produce a `Gofer.Net.Core`, `Gofer.Net.Redis` package) - this'll allow any future implementations to not also depend on the Redis packages ;).

**Comment by brthor** [comment]
Comment much appreciated @LordMike 

I realize different developers have different opinions on project structure and such. Much of my opinions are expressed in the code but allow me to explain.

I prefer to add project structure complexity as the project grows and it becomes a necessity, rather than planning for future complexity. In my experience this goes a long way in preventing premature bloat, keeps development time down, while keeping reliability high. Right now all of the things you've mentioned are intentional, and were added as a way of keeping all of the source in one repository.

For example, it doesn't make sense for the Redis implementation to exist in a separate package when there is not yet another implementation that you might choose.

I would have avoided breaking out the Utils entirely except that they are used in separate projects inside of @CoherenceApi 

I politely disagree with your conclusion that the project structure is "messy", and actually see it as quite elegant. This isn't my first .NET project and not nearly the most complicated.

**Comment by thangchung** [comment]
@brthor I'm happy to merge this PR
@LordMike Thank you for your opinion 👍

**Comment by brthor** [comment]
Thanks @thangchung 

I fixed the alphabet order just now. I'm not sure what is causing the CI failure.

```
Issues :-(
> Links 
  1. [L106] 404 https://bitbucket.org/MelbourneDeveloper/restclient-.net  
```

Is this a result of my changes?

**Pull request merged**
