### PR TITLE
Added JsonFlatFileDataStore

### PR DESCRIPTION
**Pull request by ttu**
Simple JSON flat file data store. Has a support for typed and dynamic data. Great help for prototyping etc. as data is stored to easily editable JSON file. 

https://github.com/ttu/json-flatfile-datastore
https://www.nuget.org/packages/JsonFlatFileDataStore/

Created a [JSON Fake Data REST API](https://github.com/ttu/dotnet-fake-json-server) and for that needed a JSON flat file data store that supports dynamic data and works with .NET Core.

### CODE REVIEW

**Comment by thangchung** [comment]
@ttu Thanks for your PR. But this list only for the repository that was created at least 3 months. So I will keep a look on it. Please continue to make it awesome 👍

**Comment by ttu** [comment]
@thangchung Sorry, my bad. Didn't even pay attention to that requirement, because usually all my projects take a pretty long time to "finish", so didn't even realize that this repo was still so new :)

**Comment by thangchung** [comment]
@ttu No worry about this. I will keep a look at that. Let keep the status is `open` for now.

**Comment by ttu** [comment]
Should awesome-dotnet-core hava a category for Database like awesome-dotnet has (https://github.com/quozd/awesome-dotnet#database)? 

Besides this project, at least DBreeze and NoDB would go under it. Marten ja Yessql are also in Database category in awesome-dotnet, but sometimes it is hard to say what would be the correct category for each project.

**Comment by thangchung** [comment]
@ttu Agree with you about this idea. I have added the **Database** section, could you please put your lib into this section?

**Comment by ttu** [comment]
Moved JsonFlatFileDataStore to databse section. Accidentally closed this PR while committing, but reopened it again. Is PR still ok?

**Comment by ttu** [comment]
Do you need more info about this project for review?

In awesome-dotnet repo this project  is also under [Database](https://github.com/quozd/awesome-dotnet#databse) section.

**Comment by thangchung** [comment]
@ttu I am happy to do a merge now. Thanks for the long time waiting for it. Hope you can have more PRs from you. Cheers.

**Pull request merged**
