### PR TITLE
Add UnitConversion

### PR DESCRIPTION
**Pull request by Nick-Lucas**
* [UnitConversion](https://github.com/Stratajet/UnitConversion) - Expansible Unit Conversion Library for .Net Core and .Net Framework

*Misc* may not be the best category, but a better one didn't seem to exist right now.

### CODE REVIEW

**Comment by thangchung** [comment]
@Nick-Lucas No worry. Do you have any suggestion for the category for this library?

**Comment by Nick-Lucas** [comment]
@thangchung perhaps Mathematics? I'll update the PR if you agree.

**Comment by thangchung** [comment]
@Nick-Lucas That should be fine Nick. Go ahead!

**Comment by thangchung** [comment]
@Nick-Lucas Thanks!

**Pull request merged**
