### PR TITLE
add auto history

### PR DESCRIPTION
**Pull request by ngohungphuc**

### CODE REVIEW

**Comment by ngohungphuc** [comment]
> Links 
  1. [L133] 500 https://github.com/volkanceylan/Serenity  
  2. [L484] 500 https://github.com/bchavez/Bogus

**Comment by Jogai** [comment]
Is it really awesome? This library does the same, (and more) but for EF5&6&Core: https://github.com/zzzprojects/EntityFramework-Plus#audit

**Comment by thangchung** [comment]
@Jogai Thank you for your answer. 
@ngohungphuc I have added **Arch** project in **Starter Kits**, so I think we can put it as the sub-items in this place if we all agree that this lib is awesome like @Jogai mentioned.

**Comment by ngohungphuc** [comment]
@thangchung please check it again. Thank you

**Pull request merged**
