### PR TITLE
Add links to several EntityFramework extension libraries

### PR DESCRIPTION
**Pull request by NickStrupat**

### CODE REVIEW

**Comment by thangchung** [comment]
@NickStrupat I have reviewed those libs. They are actually very cool, but I have seen that https://github.com/NickStrupat/EntityFramework.SoftDeletable is the only .NET version, not .NET Core. Do you have any plan to upgrade it? If not, please remove it out of this PR. I am happy to merge the rest of libs into my repo. Thanks 👍

**Comment by NickStrupat** [comment]
You're right about that, I was planning to upgrade all of my EF libs to EF Core 2.0 but got stuck on one and then lost focus. I do plan on updating it, especially since EF Core 2.0 has added filtering right into the framework. Anyway, can we leave this PR open for another week or two? I should be able to get to it by then.

**Comment by thangchung** [comment]
Yes, that's fine. No worry about that. Let me know when you sort out those things. I will go back and have a look at it 💯

**Comment by thangchung** [comment]
@NickStrupat I merge it now. Thanks for your PRs. Triggers and Rx are really cool 👍

**Pull request merged**
