### PR TITLE
Add Refit

### PR DESCRIPTION
**Pull request by eisenreich**

### CODE REVIEW

**Comment by thangchung** [comment]
Thank you for your PR. But could you change the order to alphabet order, please?

**Comment by totht91** [comment]
Refit is already on the list...
image

**Comment by thangchung** [comment]
@totht91 Thank you for your finding.

@eisenreich Sorry, but it has already existed, so I close it for now. Hope you can contribute another PR 👍

**Comment by srigaux** [comment]
@thangchung & @tibitoth, be careful: the Refit link does not point to the real/official repository.

It should point to: https://github.com/reactiveui/refit

**Pull request closed without merging**
