### PR TITLE
Add Inyector 

### PR DESCRIPTION
**Pull request by davidrevoledo**
Add Inyector library

### CODE REVIEW

**Comment by davidrevoledo** [comment]
@ngohungphuc done, great thanks

**Comment by ngohungphuc** [comment]
@thangchung  do you want to merge this ?

**Comment by davidrevoledo** [comment]
@ngohungphuc will be merged ? :)

**Comment by ngohungphuc** [comment]
@davidrevoledo Done. Thank you for your PR

**Comment by davidrevoledo** [comment]
thanks :)

**Pull request merged**
