### PR TITLE
Add FluentFTP

### PR DESCRIPTION
**Pull request by hgupta9**
Self nominating my library FluentFTP. Its extensively featured and well documented. In fact I created a codeproject tutorial ["Porting a .NET Framework library to .NET Core"](https://www.codeproject.com/Articles/1190475/Porting-a-NET-Framework-library-to-NET-Core) based on my real life experiences.

Added:

- [FluentFTP](https://github.com/hgupta9/FluentFTP/) - FTP and FTPS client, with extensive FTP commands, SSL/TLS connections, hashing/checksums and more.
- [Porting a .NET Framework library to .NET Core](https://www.codeproject.com/Articles/1190475/Porting-a-NET-Framework-library-to-NET-Core)

### CODE REVIEW

**Comment by hgupta9** [comment]
What are you waiting for? Is there an issue with these?

**Comment by hgupta9** [comment]
Okay will be put into Misc but the other porting article is **outdated**. Should I delete it?

**Comment by thangchung** [comment]
Yes. If you find out it useful for other people. Please do it. Thank you!

**Comment by hgupta9** [comment]
Both done.

**Comment by thangchung** [comment]
Thank you. Awesome works, man 👍

**Pull request merged**
