### PR TITLE
Add New Links

### PR DESCRIPTION
**Pull request by furesoft**

### CODE REVIEW

**Comment by Jogai** [comment]
PR title is a bit vague. Also, one project is fully documented (awesome) and the other is not.

**Comment by furesoft** [comment]
> PR title is a bit vague. Also, one project is fully documented (awesome) and the other is not.

So, which one should I remove?

**Comment by Jogai** [comment]
That programming language I think. (Not that its not awesome, but if info is so sparse, its hard to get going with)

**Comment by Jogai** [comment]
Now it looks much better!

**Comment by Jogai** [comment]
@thangchung is the maintainer, not me...

**Pull request closed without merging**
