### PR TITLE
Add CAP to [Application Frameworks]

### PR DESCRIPTION
**Pull request by yuleyule66**
Add https://github.com/dotnetcore/CAP

### CODE REVIEW

**Comment by thangchung** [comment]
Hi @yuleyule66. Just have a look at your project, I think personally that this lib is more than only in **Queue and Messaging** so that **Application Frameworks** much more appropriation, and move to that section will have the audiences can use your lib in the distributed application like SOA or Microservice patterns. Let me know how do you think?

**Comment by yuleyule66** [comment]
Yes, this project is more about system integration for SOA or Microservice. 

I have moved to **Application Frameworks**.

**Comment by yuleyule66** [comment]
Any feedback?

**Comment by thangchung** [comment]
@yuleyule66 No, it isn't. I have just been reviewing projects one by one. Please keep patient.

**Comment by ngohungphuc** [comment]
Please resolve conflict

**Pull request merged**
