### PR TITLE
Added AWS .NET Core SDK and created cloud category

### PR DESCRIPTION
**Pull request by pcgeek86**
- [x] Add AWS .NET Core SDK
- [x] Add article links to configure AWS .NET Core SDK
- [x] Add article link to authoring AWS Lambda (FaaS) using C# / .NET Core

### CODE REVIEW

**Comment by pcgeek86** [comment]
@thangchung Let me know if you need me to separate these out into separate PR's. I figured since they were all related to AWS, that they could be consolidated.

**Comment by thangchung** [comment]
@pcgeek86 Thanks for your really cool PR. But could you move item in the Cloud section to [SDKs](https://github.com/thangchung/awesome-dotnet-core#sdks) section (I don't think we need the Cloud here). And about the link I think it should be [https://github.com/aws?utf8=%E2%9C%93&q=&type=&language=c%23](https://github.com/aws?utf8=%E2%9C%93&q=&type=&language=c%23), because it will have audiences can easy to read the SDKs code in Amazon repository instead. 👍

**Comment by pcgeek86** [comment]
@thangchung I'll take care of it, thanks! :)

**Comment by pcgeek86** [comment]
I think I fixed it :) @thangchung

**Comment by thangchung** [comment]
@pcgeek86 Look good. Only need to change **AWS SDK** to the top of SDKs section (that's mean, it should be a first one in this section because we follow the alphabet order)  :)

**Comment by pcgeek86** [comment]
@thangchung Got it -- just fixed!

**Comment by thangchung** [comment]
@pcgeek86 Excellent work, man. I am happy to do a merge now 👍

**Pull request merged**
