### PR TITLE
Add Athena microservices sample

### PR DESCRIPTION
**Pull request by sponger94**
Added Athena task and time tracking assistant on microservices. Sample project.

### CODE REVIEW

**Comment by thangchung** [comment]
I just take a look at your repo. Look cool. But our team needs to look into the details to make sure you project is awesome. @ngohungphuc Please give us your idea!

**Comment by ngohungphuc** [comment]
The project look very simple

**Comment by sponger94** [comment]
Yeah, actually I found out that this violates 3months rule. @ngohungphuc do you mean that this project looks too simple at its current state because of that it's not using enough technologies, not enough code, etc. or do you mean it's too simple by design?

**Comment by ngohungphuc** [comment]
@sponger94 I mean simple by design and code

**Comment by Jogai** [comment]
KISS

"Simplicity is a prerequisite for reliability." - Edsger Dijkstra

"Simplicity is the ultimate sophistication." - Leonardo da Vinci

"Everything should be made as simple as possible, but not simpler " - Albert Einstein

"Simple can be harder than complex: You have to work hard to get your thinking clean to make it simple. But it's worth it in the end because once you get there, you can move mountains." - Steve Jobs

**Comment by sponger94** [comment]
> 
> 
> KISS
> 
> "Simplicity is a prerequisite for reliability." - Edsger Dijkstra
> 
> "Simplicity is the ultimate sophistication." - Leonardo da Vinci
> 
> "Everything should be made as simple as possible, but not simpler " - Albert Einstein
> 
> "Simple can be harder than complex: You have to work hard to get your thinking clean to make it simple. But it's worth it in the end because once you get there, you can move mountains." - Steve Jobs

Thank you random citizen! :)

**Pull request closed without merging**
