### PR TITLE
Add EntryPoint and Command-Line section

### PR DESCRIPTION
**Pull request by Nick-Lucas**
[EntryPoint](https://github.com/Nick-Lucas/EntryPoint) - Lightweight declarative CLI argument parser for all modern .Net platforms

### CODE REVIEW

**Comment by thangchung** [comment]
@Nick-Lucas When did your project create? The awesome project has a rule that the project has existed at least 30 days [here](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md). I saw the history of it, maybe just around 4,5 days ago, right?

**Comment by Nick-Lucas** [comment]
Oops sorry! I didn't recheck rules as I've made a number of submissions in the past.

Happy to hold off and resubmit down the line, although I can say I've written this because I need to use it, so I won't be abandoning it in a few days. It's also pretty feature complete already.

**Comment by thangchung** [comment]
@Nick-Lucas Just keep the PR here until next month. I think it is good if you can write some document or article to show people out there know about your lib 👍

**Comment by Nick-Lucas** [comment]
Sure thing! Good timing on the suggestion too; I built the [website](https://github.com/Nick-Lucas/EntryPoint) today.
Happy new year 😄

**Comment by thangchung** [comment]
@Nick-Lucas Your repository looks good now. Congrats 👍

**Comment by Nick-Lucas** [comment]
Hi @thangchung, the library is now at v1.0.0, I'm also going to update this PR as I've changed the way I describe it slightly

**Comment by thangchung** [comment]
@Nick-Lucas I thought why do we just put your lib into the Tools section. I think it will support for some of the tasks relate to deployment and diagnostic.

**Comment by Nick-Lucas** [comment]
Can do, I added CLI because other trackers have that section; but considering the lack of many tools to go there, right now, it might make sense.

**Comment by thangchung** [comment]
@Nick-Lucas Thanks, Nick. Sorry for this very long review. I am happy to merge it 👍

**Pull request merged**
