### PR TITLE
Add ServiceStack.Text.

### PR DESCRIPTION
**Pull request by chumakov-ilya**
ServiceStack now has support for .NET Core.
http://docs.servicestack.net/releases/v4.5.2.html
https://www.nuget.org/packages/ServiceStack.Text.Core
https://github.com/ServiceStack/ServiceStack.Text

### CODE REVIEW

**Comment by thangchung** [comment]
@chumakov-ilya Thanks for your information. I have a look into 2 PRs ([#39](https://github.com/thangchung/awesome-dotnet-core/pull/39) and [#38](https://github.com/thangchung/awesome-dotnet-core/pull/38)) that you pulled into. Just have a quick thought that why don't we put an item with named is `Service Stack` into the [Application Frameworks](https://github.com/thangchung/awesome-dotnet-core#application-frameworks)? Because I think that stack will help people build up the applications (Web & API), not only `ServiceStack.OrmLite.Core` and `ServiceStack.Text.Core`. How do you think?

**Comment by chumakov-ilya** [comment]
@thangchung, I agree that Frameworks section is the good place for https://github.com/ServiceStack/ServiceStack. However, the link to ServiceStack serializer or ORM would be helpful too because these packages may be used independently and without the whole ServiceStack framework.

**Comment by thangchung** [comment]
@chumakov-ilya  Agreed. But could you change the order of ServiceStack.Text lib. We follow alphabet order for this list. Thanks.

**Comment by chumakov-ilya** [comment]
@thangchung, sorry, I missed that. Fixed.

**Pull request merged**
