### PR TITLE
Add Serenity template framework

### PR DESCRIPTION
**Pull request by minhhungit**
Serenity is an ASP.NET MVC / TypeScript application platform designed to simplify and shorten development of data-centric business applications with a service based architecture.

Reference link: 
- Homepage: http://serenity.is/
- Github: https://github.com/volkanceylan/Serenity
- A review page: https://github.com/volkanceylan/Serenity/issues/3103

### CODE REVIEW

**Comment by thangchung** [comment]
@minhhungit Thanks for your PR. It is really awesome, but could you please change the link to Github link instead of http://serenity.is so that our readers can easy to find and read the source code of it.

**Comment by minhhungit** [comment]
@thangchung I updated it, please check again

**Comment by thangchung** [comment]
@minhhungit Looks cool now. But one little bitty thing, please change your library to the alphabet order in this section. Thank you.

**Comment by ngohungphuc** [comment]
Look great

**Comment by thangchung** [comment]
Nothing else. Thank you for your PR. Really cool!

**Pull request merged**
