### PR TITLE
Added GrandNode to ecommerce platforms

### PR DESCRIPTION
**Pull request by PatrykPorabik**

### CODE REVIEW

**Comment by thangchung** [comment]
@PatrykPorabik Is it developed by the nopCommerce team?

**Comment by PatrykPorabik** [comment]
@thangchung No, we modified it 3 years ago. We changed database engine from MSSQL to MongoDB. It's based on nopCommerce but it's independent software not related with nopCommerce team.

**Comment by PatrykPorabik** [comment]
@ngohungphuc Done

**Comment by thangchung** [comment]
@PatrykPorabik Thank you for your explanation. It is the really cool project 👍

**Pull request merged**
