### PR TITLE
Add EntityFrameworkCore.DataEncryption library

### PR DESCRIPTION
**Pull request by Eastrall**
Hi, I developed an EntityFrameworkCore plugin that handles data encryption.

Check it out here: https://github.com/Eastrall/EntityFrameworkCore.DataEncryption

### CODE REVIEW

**Comment by Eastrall** [comment]
Any news for this PR ?

**Comment by thangchung** [comment]
@Eastrall Have you used this library in any projects?

**Comment by Eastrall** [comment]
> @Eastrall Have you used this library in any projects?

Yes I did. I'm am still using it on my MMORPG emulator named [Rhisis](https://github.com/Eastrall/Rhisis).
Also, this library has been update to support Entity Framework Core 3 and .NET Standard 2.1. It also has 10K downloads on nuget already.

**Comment by Eastrall** [comment]
Any news?
For info, in December, we were at 10K downloads in total, and two months later we have 19K downloads 😄

**Pull request merged**
