### PR TITLE
Adding Exploring .NET Core with Microservices, ASP.NET Core, and Entity Framework Core to the book list

### PR DESCRIPTION
**Pull request by Charismatron**
Hi,

Would you be so kind as to add Exploring .Net Core, a free eBook sampler from Manning Publications, to your book list?

Thanks:)

### CODE REVIEW

**Comment by Jogai** [comment]
Only a sample doesnt seem that awesome...

**Comment by Charismatron** [comment]
I assure you that it's pretty awesome. Perhaps the word sampler makes it seem less so. It would be better to describe it as a free eBook with selected chapters (from other Manning books) that give an intro and overview into what you can do with .NET Core's various tools and frameworks, using practical examples. If you're still not convinced, download it and give it a read - it's free!

**Comment by thangchung** [comment]
@Charismatron I get back to your PR. Please could you change the order to alphabet order 👍

**Comment by Charismatron** [comment]
Change made!

**Pull request merged**
