### PR TITLE
add DataGenerator

### PR DESCRIPTION
**Pull request by pwelter34**
add DataGenerator <https://github.com/loresoft/DataGenerator>

### CODE REVIEW

**Comment by pwelter34** [comment]
From what I can tell, Faker seems to just give random values. 

```
var u = new User();
u.Name= Faker.Name.FullName()
u.EmailAddress = Faker.Internet.Email(); 
```

DataGenerator is designed to fill the whole object graph using smart defaults

```
var user = Generator.Default.Single<User>();
```

**Comment by LordMike** [comment]
Ah, that's neat.

**Comment by bchavez** [comment]
If you don't like defining rules manually, you can try a cool community extension to **Bogus** called **AutoBogus** written by Nick Dodd here:

https://github.com/nickdodd79/AutoBogus/

**Comment by LordMike** [comment]
@bchavez you should add this to the `awesome-dotnet-core` list, as a sub-item to Bogus.

**Comment by ngohungphuc** [comment]
Close this pr due to inactivity

**Pull request closed without merging**
