### PR TITLE
Create BuiltWithDotNet.md

### PR DESCRIPTION
**Pull request by Corstiaan84**
Link: https://builtwithdot.net

### CODE REVIEW

**Comment by Corstiaan84** [comment]
@thangchung Sure! That's probably even a better category.

**Comment by Corstiaan84** [comment]
@thangchung May I gently inquire about the status of this? :-)

**Comment by Corstiaan84** [comment]
@thangchung Made the change. It is ok?

**Comment by ngohungphuc** [comment]
What I mean move to community section in read me file

**Comment by Corstiaan84** [comment]
Should be good to go 👍

**Comment by ngohungphuc** [comment]
Thank you for your pr

**Pull request merged**
