### PR TITLE
Update README.MD

### PR DESCRIPTION
**Pull request by snehaldkshah**
Gluu - Offers Commercial OAuth 2.0 client software called Oxd with different programming languages including Csharp.

### CODE REVIEW

**Comment by thangchung** [comment]
@snehaldkshah The first of all, I wanna say thanks to your contribution, but looks like the project you submited to is not a .NET Core project. So that I cannot approve it. Is there any odx server for .NET Core out there?

**Comment by snehaldkshah** [comment]
Hello @thangchung,
Yes it is .net C# core library which communicates with oxd-server. 
This library can be used as plug and play.

**Comment by snehaldkshah** [comment]
Hello @thangchung,
Can you please tell me status for this pull request?

**Comment by thangchung** [comment]
@snehaldkshah I could not find out any source code that implemented .NET Core. Is it your repo at https://github.com/GluuFederation/oxd-csharp/tree/master/CSharp? There is no project.json file or new template comes from Visual Studio 2017 (Sdk="Microsoft.NET.Sdk") in that repo. Or anywhere else that your .NET Core source codes committed to?

**Pull request closed without merging**
