### PR TITLE
Add OpenCQRS to Queue and Messaging

### PR DESCRIPTION
**Pull request by lucabriguglia**

### CODE REVIEW

**Comment by SebastianStehle** [comment]
I have absolutely no idea what it is. You should explain your definition of a mediator.

**Comment by lucabriguglia** [comment]
What it does is explained [here](https://github.com/Weapsy/Weapsy.Mediator).

**Comment by ngohungphuc** [comment]
@thangchung please review this one

**Comment by lucabriguglia** [comment]
Hi @ngohungphuc, order changed :-)

**Pull request merged**
